### ISSUE TITLE
If no mic app not start

### ISSUE THREAD

**Issue by retrodaredevil** [retrodaredevil/led-machine#2]
For me to fix later:
```
/usr/local/lib/python3.7/dist-packages/pydub-0.25.1-py3.7.egg/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Initializing SlackHelper
Going to try to connect
Connected
Finished initializing SlackHelper
Traceback (most recent call last):
  File "/usr/local/bin/led-machine", line 11, in <module>
    load_entry_point('led-machine==0.1', 'console_scripts', 'led-machine')()
  File "/usr/local/lib/python3.7/dist-packages/led_machine-0.1-py3.7.egg/led_machine/__init__.py", line 69, in main
  File "/usr/local/lib/python3.7/dist-packages/led_machine-0.1-py3.7.egg/led_machine/volume.py", line 183, in __init__
  File "/usr/local/lib/python3.7/dist-packages/led_machine-0.1-py3.7.egg/led_machine/volume.py", line 144, in __init__
  File "/usr/local/lib/python3.7/dist-packages/led_machine-0.1-py3.7.egg/led_machine/volume.py", line 58, in __init__
  File "/usr/lib/python3/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9996] Invalid input device (no default output device)
```

**Comment by retrodaredevil** [comment]
One of my previous commits fixed this, although volume detection on RPis still sucks even when I did get this working
