### ISSUE TITLE
Error from 999999 speed

### ISSUE THREAD

**Issue by retrodaredevil** [retrodaredevil/led-machine#4]
```
Dec 01 23:08:53 raspberrypi run.sh[2136]: Got text: 'hyper'
Dec 01 23:08:53 raspberrypi run.sh[2136]: Got text: '999999 speed'
Dec 01 23:08:53 raspberrypi run.sh[2136]: Traceback (most recent call last):
Dec 01 23:08:53 raspberrypi run.sh[2136]:   File "/usr/local/bin/led-machine", line 11, in <module>
Dec 01 23:08:53 raspberrypi run.sh[2136]:     load_entry_point('led-machine==0.1', 'console_scripts', 'led-machine')()
Dec 01 23:08:53 raspberrypi run.sh[2136]:   File "/usr/local/lib/python3.7/dist-packages/led_machine-0.1-py3.7.egg/led_machine/__init__.py", line 93, in main
Dec 01 23:08:53 raspberrypi run.sh[2136]:   File "/usr/local/lib/python3.7/dist-packages/led_machine-0.1-py3.7.egg/led_machine/alter.py", line 69, in alter_pixel
Dec 01 23:08:53 raspberrypi run.sh[2136]:   File "/usr/local/lib/python3.7/dist-packages/led_machine-0.1-py3.7.egg/led_machine/blend.py", line 25, in alter_pixel
Dec 01 23:08:53 raspberrypi run.sh[2136]:   File "/usr/local/lib/python3.7/dist-packages/led_machine-0.1-py3.7.egg/led_machine/blend.py", line 21, in _get_alter
Dec 01 23:08:53 raspberrypi run.sh[2136]: IndexError: list index out of range
Dec 01 23:08:53 raspberrypi systemd[1]: led-machine.service: Main process exited, code=exited, status=1/FAILURE
Dec 01 23:08:53 raspberrypi systemd[1]: led-machine.service: Failed with result 'exit-code'.
```

**Comment by retrodaredevil** [comment]
Another of the same error:
```
Dec 01 23:10:59 raspberrypi systemd[1]: Started Service for LED Machine.
Dec 01 23:12:11 raspberrypi run.sh[4956]: Initializing SlackHelper
Dec 01 23:12:11 raspberrypi run.sh[4956]: Going to try to connect
Dec 01 23:12:11 raspberrypi run.sh[4956]: Connected
Dec 01 23:12:11 raspberrypi run.sh[4956]: Finished initializing SlackHelper
Dec 01 23:12:11 raspberrypi run.sh[4956]: Got text: '(slow rainbow) ~ (hyper rainbow)'
Dec 01 23:12:11 raspberrypi run.sh[4956]: Got text: '99999 speed'
Dec 01 23:12:11 raspberrypi run.sh[4956]: Traceback (most recent call last):
Dec 01 23:12:11 raspberrypi run.sh[4956]:   File "/usr/local/bin/led-machine", line 11, in <module>
Dec 01 23:12:11 raspberrypi run.sh[4956]:     load_entry_point('led-machine==0.1', 'console_scripts', 'led-machine')()
Dec 01 23:12:11 raspberrypi run.sh[4956]:   File "/usr/local/lib/python3.7/dist-packages/led_machine-0.1-py3.7.egg/led_machine/__init__.py", line 93, in main
Dec 01 23:12:11 raspberrypi run.sh[4956]:   File "/usr/local/lib/python3.7/dist-packages/led_machine-0.1-py3.7.egg/led_machine/alter.py", line 69, in alter_pixel
Dec 01 23:12:11 raspberrypi run.sh[4956]:   File "/usr/local/lib/python3.7/dist-packages/led_machine-0.1-py3.7.egg/led_machine/blend.py", line 25, in alter_pixel
Dec 01 23:12:11 raspberrypi run.sh[4956]:   File "/usr/local/lib/python3.7/dist-packages/led_machine-0.1-py3.7.egg/led_machine/blend.py", line 21, in _get_alter
Dec 01 23:12:11 raspberrypi run.sh[4956]: IndexError: list index out of range
Dec 01 23:12:11 raspberrypi systemd[1]: led-machine.service: Main process exited, code=exited, status=1/FAILURE
Dec 01 23:12:11 raspberrypi systemd[1]: led-machine.service: Failed with result 'exit-code'.
```
